version: '3.3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
